analogs:
- !!python/tuple [176, 16]
- !!python/tuple [176, 1]
- !!python/tuple [176, 2]
- !!python/tuple [144, 37]
- !!python/tuple [144, 39]
- !!python/tuple [144, 41]
- !!python/tuple [144, 43]
- !!python/tuple [144, 45]
- !!python/tuple [144, 47]
- !!python/tuple [144, 49]
- !!python/tuple [144, 51]
- !!python/tuple [144, 36]
- !!python/tuple [144, 38]
- !!python/tuple [144, 40]
- !!python/tuple [144, 42]
- !!python/tuple [144, 44]
- !!python/tuple [144, 46]
- !!python/tuple [144, 48]
- !!python/tuple [144, 50]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [144, 57]
- !!python/tuple [144, 59]
- !!python/tuple [144, 61]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 67]
- !!python/tuple [144, 52]
- !!python/tuple [144, 54]
- !!python/tuple [144, 56]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 62]
- !!python/tuple [144, 64]
- !!python/tuple [144, 66]
- !!python/tuple [144, 69]
- !!python/tuple [144, 71]
- !!python/tuple [144, 73]
- !!python/tuple [144, 75]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 81]
- !!python/tuple [144, 83]
- !!python/tuple [144, 68]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 74]
- !!python/tuple [144, 76]
- !!python/tuple [144, 78]
- !!python/tuple [144, 80]
- !!python/tuple [144, 82]
- !!python/tuple [144, 85]
- !!python/tuple [144, 87]
- !!python/tuple [144, 89]
- !!python/tuple [144, 91]
- !!python/tuple [144, 93]
- !!python/tuple [144, 95]
- !!python/tuple [144, 97]
- !!python/tuple [144, 99]
- !!python/tuple [144, 84]
- !!python/tuple [144, 86]
- !!python/tuple [144, 88]
- !!python/tuple [144, 90]
- !!python/tuple [144, 92]
- !!python/tuple [144, 94]
- !!python/tuple [144, 96]
- !!python/tuple [144, 98]
buttons: []
device_name: nanoPAD2 MIDI 1
