analogs:
- !!python/tuple [176, 16]
- !!python/tuple [176, 17]
- !!python/tuple [176, 18]
- !!python/tuple [176, 19]
- !!python/tuple [176, 20]
- !!python/tuple [176, 21]
- !!python/tuple [176, 22]
- !!python/tuple [176, 23]
- !!python/tuple [176, 0]
- !!python/tuple [176, 1]
- !!python/tuple [176, 2]
- !!python/tuple [176, 3]
- !!python/tuple [176, 4]
- !!python/tuple [176, 5]
- !!python/tuple [176, 6]
- !!python/tuple [176, 7]
- !!python/tuple [176, 58]
- !!python/tuple [176, 59]
- !!python/tuple [176, 46]
- !!python/tuple [176, 60]
- !!python/tuple [176, 61]
- !!python/tuple [176, 62]
- !!python/tuple [176, 43]
- !!python/tuple [176, 44]
- !!python/tuple [176, 42]
- !!python/tuple [176, 41]
- !!python/tuple [176, 45]
- !!python/tuple [176, 32]
- !!python/tuple [176, 48]
- !!python/tuple [176, 64]
- !!python/tuple [176, 33]
- !!python/tuple [176, 49]
- !!python/tuple [176, 65]
- !!python/tuple [176, 34]
- !!python/tuple [176, 50]
- !!python/tuple [176, 66]
- !!python/tuple [176, 35]
- !!python/tuple [176, 51]
- !!python/tuple [176, 67]
- !!python/tuple [176, 36]
- !!python/tuple [176, 52]
- !!python/tuple [176, 68]
- !!python/tuple [176, 37]
- !!python/tuple [176, 53]
- !!python/tuple [176, 69]
- !!python/tuple [176, 38]
- !!python/tuple [176, 54]
- !!python/tuple [176, 70]
- !!python/tuple [176, 39]
- !!python/tuple [176, 55]
- !!python/tuple [176, 71]
buttons: []
device_name: nanoKONTROL2 MIDI 1
