analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
- !!python/tuple [144, 0, false, 33]
- !!python/tuple [144, 0, false, 34]
- !!python/tuple [144, 0, false, 35]
- !!python/tuple [144, 0, false, 36]
- !!python/tuple [144, 0, false, 37]
- !!python/tuple [144, 0, false, 38]
- !!python/tuple [144, 0, false, 39]
- !!python/tuple [144, 0, false, 40]
- !!python/tuple [144, 0, false, 41]
- !!python/tuple [144, 0, false, 42]
- !!python/tuple [144, 0, false, 43]
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
- !!python/tuple [144, 0, false, 33]
- !!python/tuple [144, 0, false, 34]
- !!python/tuple [144, 0, false, 35]
- !!python/tuple [144, 0, false, 36]
- !!python/tuple [144, 0, false, 37]
- !!python/tuple [144, 0, false, 38]
- !!python/tuple [144, 0, false, 39]
- !!python/tuple [144, 0, false, 40]
- !!python/tuple [144, 0, false, 41]
- !!python/tuple [144, 0, false, 42]
- !!python/tuple [144, 0, false, 43]
- !!python/tuple [144, 0, false, 44]
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
- !!python/tuple [144, 0, false, 33]
- !!python/tuple [144, 0, false, 34]
- !!python/tuple [144, 0, false, 35]
- !!python/tuple [144, 0, false, 36]
- !!python/tuple [144, 0, false, 37]
- !!python/tuple [144, 0, false, 38]
- !!python/tuple [144, 0, false, 39]
- !!python/tuple [144, 0, false, 40]
- !!python/tuple [144, 0, false, 41]
- !!python/tuple [144, 0, false, 42]
- !!python/tuple [144, 0, false, 43]
- !!python/tuple [144, 0, false, 44]
- !!python/tuple [144, 0, false, 46]
- !!python/tuple [144, 0, false, 47]
- !!python/tuple [144, 0, false, 48]
- !!python/tuple [144, 0, false, 49]
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
- !!python/tuple [144, 0, false, 33]
- !!python/tuple [144, 0, false, 34]
- !!python/tuple [144, 0, false, 35]
- !!python/tuple [144, 0, false, 36]
- !!python/tuple [144, 0, false, 37]
- !!python/tuple [144, 0, false, 38]
- !!python/tuple [144, 0, false, 39]
- !!python/tuple [144, 0, false, 40]
- !!python/tuple [144, 0, false, 41]
- !!python/tuple [144, 0, false, 42]
- !!python/tuple [144, 0, false, 43]
- !!python/tuple [144, 0, false, 44]
- !!python/tuple [144, 0, false, 46]
- !!python/tuple [144, 0, false, 47]
- !!python/tuple [144, 0, false, 48]
- !!python/tuple [144, 0, false, 49]
- !!python/tuple [176, 0, false, 1]
- !!python/tuple [176, 0, false, 2]
- !!python/tuple [176, 0, false, 3]
- !!python/tuple [176, 0, false, 4]
analogs:
- !!python/tuple [176, 12]
- !!python/tuple [176, 29]
- !!python/tuple [176, 71]
- !!python/tuple [176, 72]
- !!python/tuple [176, 5]
- !!python/tuple [176, 1]
- !!python/tuple [176, 18]
- !!python/tuple [176, 77]
- !!python/tuple [176, 82]
- !!python/tuple [176, 14]
- !!python/tuple [176, 19]
- !!python/tuple [176, 15]
- !!python/tuple [176, 22]
- !!python/tuple [176, 74]
- !!python/tuple [144, 77]
- !!python/tuple [144, 79]
- !!python/tuple [144, 82]
- !!python/tuple [144, 84]
- !!python/tuple [144, 67]
- !!python/tuple [144, 70]
- !!python/tuple [144, 72]
- !!python/tuple [144, 75]
- !!python/tuple [144, 58]
- !!python/tuple [144, 60]
- !!python/tuple [144, 63]
- !!python/tuple [144, 65]
- !!python/tuple [144, 48]
- !!python/tuple [144, 51]
- !!python/tuple [144, 53]
- !!python/tuple [144, 55]
- !!python/tuple [176, 90]
- !!python/tuple [176, 91]
- !!python/tuple [176, 92]
buttons: []
device_name: QUNEO MIDI 1
output:
- !!python/tuple [144, 0, false, 0]
- !!python/tuple [144, 0, false, 1]
- !!python/tuple [144, 0, false, 2]
- !!python/tuple [144, 0, false, 3]
- !!python/tuple [144, 0, false, 4]
- !!python/tuple [144, 0, false, 5]
- !!python/tuple [144, 0, false, 6]
- !!python/tuple [144, 0, false, 7]
- !!python/tuple [144, 0, false, 8]
- !!python/tuple [144, 0, false, 9]
- !!python/tuple [144, 0, false, 10]
- !!python/tuple [144, 0, false, 11]
- !!python/tuple [144, 0, false, 12]
- !!python/tuple [144, 0, false, 13]
- !!python/tuple [144, 0, false, 14]
- !!python/tuple [144, 0, false, 15]
- !!python/tuple [144, 0, false, 16]
- !!python/tuple [144, 0, false, 17]
- !!python/tuple [144, 0, false, 18]
- !!python/tuple [144, 0, false, 19]
- !!python/tuple [144, 0, false, 20]
- !!python/tuple [144, 0, false, 21]
- !!python/tuple [144, 0, false, 22]
- !!python/tuple [144, 0, false, 23]
- !!python/tuple [144, 0, false, 24]
- !!python/tuple [144, 0, false, 25]
- !!python/tuple [144, 0, false, 26]
- !!python/tuple [144, 0, false, 27]
- !!python/tuple [144, 0, false, 28]
- !!python/tuple [144, 0, false, 29]
- !!python/tuple [144, 0, false, 30]
- !!python/tuple [144, 0, false, 31]
- !!python/tuple [144, 0, false, 33]
- !!python/tuple [144, 0, false, 34]
- !!python/tuple [144, 0, false, 35]
- !!python/tuple [144, 0, false, 36]
- !!python/tuple [144, 0, false, 37]
- !!python/tuple [144, 0, false, 38]
- !!python/tuple [144, 0, false, 39]
- !!python/tuple [144, 0, false, 40]
- !!python/tuple [144, 0, false, 41]
- !!python/tuple [144, 0, false, 42]
- !!python/tuple [144, 0, false, 43]
- !!python/tuple [144, 0, false, 44]
- !!python/tuple [144, 0, false, 46]
- !!python/tuple [144, 0, false, 47]
- !!python/tuple [144, 0, false, 48]
- !!python/tuple [144, 0, false, 49]
- !!python/tuple [176, 0, false, 1]
- !!python/tuple [176, 0, false, 2]
- !!python/tuple [176, 0, false, 3]
- !!python/tuple [176, 0, false, 4]
- !!python/tuple [176, 0, false, 5]
- !!python/tuple [176, 0, false, 6]
- !!python/tuple [176, 0, false, 7]
- !!python/tuple [176, 0, false, 8]
- !!python/tuple [176, 0, false, 9]
- !!python/tuple [176, 0, false, 10]
- !!python/tuple [176, 0, false, 11]
