#!/usr/bin/env python

import rospy

from app_scheduler import AppScheduler


if __name__ == '__main__':
    rospy.init_node('app_scheduler')
    robot_name = rospy.get_param('/robot/name', 'robot')
    yaml_path = rospy.get_param('~yaml_path')
    duration = rospy.get_param('~duration', 1)
    update_duration = rospy.get_param('~update_duration', 60)
    scheduler = AppScheduler(robot_name, yaml_path, duration, update_duration)
    rospy.spin()
