bool       bool_atom
bool[4]    bool_array
uint8      uint8_atom
uint8[4]   uint8_array
int8       int8_atom
int8[4]    int8_array
uint16     uint16_atom
uint16[4]  uint16_array
int32      int32_atom
int32[4]   int32_array
uint32     uint32_atom
uint32[4]  uint32_array
int64      int64_atom
int64[4]   int64_array
uint64     uint64_atom
uint64[4]  uint64_array
float32    float32_atom
float32[4] float32_array
float64    float64_atom
float64[4] float64_array

# int8, not supported
# string, not supported
# time, not supported
# duration, not supported
