# sensor for Tablet

float64 accelerometer_x
float64 accelerometer_y
float64 accelerometer_z

float64 magneticfield_x
float64 magneticfield_y
float64 magneticfield_z

float64 gyroscope_x
float64 gyroscope_y
float64 gyroscope_z

float64 light

float64 pressure

bool proximity

float64 gravity_x
float64 gravity_y
float64 gravity_z

float64 linear_acceleration_x
float64 linear_acceleration_y
float64 linear_acceleration_z

float64 rotation_vector_x
float64 rotation_vector_y
float64 rotation_vector_z
float64 rotation_vector_optional

float64 orientation_x
float64 orientation_y
float64 orientation_z

float64 relative_humidity

float64 temperature

float64 ambient_temperature





