APIHOST: https://api.apigw.smt.docomo.ne.jp/dialogue/v1/dialogue
APIKEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
CONTEXT: hogehoge
NICKNAME: AAAAA
NICKNAME_Y: AAAAA
SEX: 男
BLOODTYPE: A
BIRTHDATEY: 19XX
BIRTHDATEM: 1
BIRTHDATED: 23
AGE: 45
CONSTELLATIONS: 双子座
PLACE: 東京
